In [1]:
import sys
sys.path.append('..')

In [2]:
import tensorflow as tf
from keras_tweaks import dense_sparse_matmul

In [3]:
# 1x3 row vector
h = tf.constant([1., 2., 3.])

# 3x4 sparse matrix
W = tf.sparse.SparseTensor(
    indices=([0, 1], [1, 1], [1, 2], [2, 0], [2, 2], [0, 3], [2, 3]),
    values=[1., 2., 3., 4., 5., 6., 7.],
    dense_shape=(3, 4))
W = tf.sparse.reorder(W)

# result is a 1x4 row vector
net = dense_sparse_matmul(h, W)

In [4]:
print("h")
tf.print(h)

print("W:")
tf.print(tf.sparse.to_dense(W))

print("net:")
tf.print(net)

h
[1 2 3]
W:
[[0 1 0 6]
 [0 2 3 0]
 [4 0 5 7]]
net:
[[12 5 21 27]]
