In [1]:
import sys
sys.path.append('..')

# Block Matrix

In [2]:
import tensorflow as tf
from keras_tweaks import get_sparsity_pattern

n_rows, n_cols = 10, 12
mat_pattern = get_sparsity_pattern('block', min(n_rows, n_cols), block_sizes=[3, 1, 2])
mat_values = range(1, len(mat_pattern)+1)

mat = tf.sparse.SparseTensor(
    dense_shape=(n_rows, n_cols),
    indices=mat_pattern,
    values=mat_values)

print(tf.sparse.to_dense(mat))

tf.Tensor(
[[ 1  2  3  0  0  0  0  0  0  0  0  0]
 [ 4  5  6  0  0  0  0  0  0  0  0  0]
 [ 7  8  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 11 12  0  0  0  0  0  0]
 [ 0  0  0  0 13 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 15 16 17  0  0  0]
 [ 0  0  0  0  0  0 18 19 20  0  0  0]
 [ 0  0  0  0  0  0 21 22 23  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 24  0  0]], shape=(10, 12), dtype=int32)


# tril und triu

In [3]:
mat_pattern = get_sparsity_pattern('triu', n=5, k=-1)

mat = tf.sparse.SparseTensor(
    dense_shape=(5, 5),
    values=range(1, len(mat_pattern)+1),
    indices=mat_pattern)

print(tf.sparse.to_dense(mat))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 0  0  5  6  7]
 [ 0  0  0  8  9]
 [ 0  0  0  0 10]
 [ 0  0  0  0  0]], shape=(5, 5), dtype=int32)


In [4]:
# tril is the transposed of triu
mat_pattern = tf.keras.backend.reverse(mat_pattern, axes=1)

mat = tf.sparse.reorder(tf.sparse.SparseTensor(
    dense_shape=(5, 5),
    values=range(1, len(mat_pattern)+1),
    indices=mat_pattern))

print(tf.sparse.to_dense(mat))

tf.Tensor(
[[ 0  0  0  0  0]
 [ 1  0  0  0  0]
 [ 2  5  0  0  0]
 [ 3  6  8  0  0]
 [ 4  7  9 10  0]], shape=(5, 5), dtype=int32)
